import { Tool, ToolCategory } from "@shared/schema";

export const tools: Tool[] = [
  // Calculators
  {
    id: "general-calculator",
    name: "General Calculator",
    description: "Basic arithmetic calculations with history",
    category: "calculators",
    icon: "calculator",
    clientOnly: true,
    popular: true,
    tags: ["math", "arithmetic", "calculator"],
  },
  {
    id: "scientific-calculator",
    name: "Scientific Calculator",
    description: "Advanced mathematical functions and operations",
    category: "calculators",
    icon: "calculator",
    clientOnly: true,
    popular: false,
    tags: ["math", "scientific", "trigonometry"],
  },
  {
    id: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages, discounts, and changes",
    category: "calculators",
    icon: "percent",
    clientOnly: true,
    popular: false,
    tags: ["percentage", "discount", "math"],
  },
  {
    id: "bmi-calculator",
    name: "BMI Calculator",
    description: "Calculate Body Mass Index quickly",
    category: "calculators",
    icon: "Heart",
    clientOnly: true,
    popular: true,
    tags: ["health", "bmi", "fitness"],
  },
  {
    id: "age-calculator",
    name: "Age Calculator",
    description: "Calculate age in years, months, and days",
    category: "calculators",
    icon: "calendar",
    clientOnly: true,
    popular: false,
    tags: ["age", "date", "time"],
  },
  {
    id: "date-calculator",
    name: "Date Calculator",
    description: "Calculate differences between dates",
    category: "calculators",
    icon: "calendar-days",
    clientOnly: true,
    popular: false,
    tags: ["date", "time", "duration"],
  },
  {
    id: "loan-calculator",
    name: "Loan Calculator",
    description: "Calculate EMI, interest, and payment schedules",
    category: "calculators",
    icon: "banknote",
    clientOnly: true,
    popular: false,
    tags: ["loan", "emi", "finance"],
  },
  {
    id: "investment-calculator",
    name: "Investment Calculator",
    description: "Calculate returns on investments with compound interest",
    category: "calculators",
    icon: "trending-up",
    clientOnly: true,
    popular: true,
    tags: ["investment", "returns", "finance", "compound"],
  },
  {
    id: "calorie-calculator",
    name: "Calorie Calculator",
    description: "Calculate daily calorie needs based on activity level",
    category: "calculators",
    icon: "apple",
    clientOnly: true,
    popular: true,
    tags: ["calories", "diet", "fitness", "health"],
  },
  {
    id: "compound-interest-calculator",
    name: "Compound Interest Calculator",
    description: "Calculate compound interest with detailed breakdown",
    category: "calculators",
    icon: "piggy-bank",
    clientOnly: true,
    popular: false,
    tags: ["interest", "compound", "finance", "investment"],
  },
  {
    id: "body-fat-calculator",
    name: "Body Fat Calculator",
    description: "Estimate body fat percentage using measurements",
    category: "calculators",
    icon: "activity",
    clientOnly: true,
    popular: false,
    tags: ["body fat", "fitness", "health", "measurements"],
  },
  {
    id: "tax-gst-calculator",
    name: "Tax / GST Calculator",
    description: "Calculate tax amounts and inclusive/exclusive pricing",
    category: "calculators",
    icon: "receipt",
    clientOnly: true,
    popular: false,
    tags: ["tax", "gst", "finance", "business"],
  },

  // Converters
  {
    id: "currency-converter",
    name: "Currency Converter",
    description: "Live exchange rates and conversions",
    category: "converters",
    icon: "banknote",
    clientOnly: false,
    popular: true,
    tags: ["currency", "exchange", "money"],
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    description: "Convert between various units",
    category: "converters",
    icon: "ruler",
    clientOnly: true,
    popular: true,
    tags: ["units", "measurement", "conversion"],
  },
  {
    id: "timezone-converter",
    name: "Time Zone Converter",
    description: "Convert time across different time zones",
    category: "converters",
    icon: "clock",
    clientOnly: true,
    popular: false,
    tags: ["time", "timezone", "clock"],
  },
  {
    id: "number-system-converter",
    name: "Number System Converter",
    description: "Convert between binary, decimal, hex, and octal",
    category: "converters",
    icon: "binary",
    clientOnly: true,
    popular: false,
    tags: ["binary", "hex", "decimal", "programming"],
  },
  {
    id: "text-case-converter",
    name: "Text Case Converter",
    description: "Convert text to different cases",
    category: "converters",
    icon: "type",
    clientOnly: true,
    popular: false,
    tags: ["text", "case", "uppercase", "lowercase"],
  },
  {
    id: "temperature-converter",
    name: "Temperature Converter",
    description: "Convert between Celsius, Fahrenheit, and Kelvin",
    category: "converters",
    icon: "thermometer",
    clientOnly: true,
    popular: true,
    tags: ["temperature", "celsius", "fahrenheit", "kelvin"],
  },
  {
    id: "json-to-xml-converter",
    name: "JSON to XML Converter",
    description: "Convert JSON data to XML format",
    category: "converters",
    icon: "code",
    clientOnly: true,
    popular: false,
    tags: ["json", "xml", "data", "conversion"],
  },
  {
    id: "xml-to-json-converter",
    name: "XML to JSON Converter",
    description: "Convert XML data to JSON format",
    category: "converters",
    icon: "code",
    clientOnly: true,
    popular: false,
    tags: ["xml", "json", "data", "conversion"],
  },
  {
    id: "csv-to-json-converter",
    name: "CSV to JSON Converter",
    description: "Convert CSV files to JSON format",
    category: "converters",
    icon: "table",
    clientOnly: true,
    popular: false,
    tags: ["csv", "json", "data", "conversion"],
  },
  {
    id: "json-to-csv-converter",
    name: "JSON to CSV Converter",
    description: "Convert JSON data to CSV format",
    category: "converters",
    icon: "table",
    clientOnly: true,
    popular: false,
    tags: ["json", "csv", "data", "conversion"],
  },

  // Image Tools
  {
    id: "image-resizer",
    name: "Image Resizer",
    description: "Resize images while maintaining quality",
    category: "image-tools",
    icon: "maximize",
    clientOnly: false,
    popular: true,
    tags: ["image", "resize", "photo"],
  },
  {
    id: "image-compressor",
    name: "Image Compressor",
    description: "Reduce image file sizes",
    category: "image-tools",
    icon: "minimize",
    clientOnly: false,
    popular: false,
    tags: ["image", "compress", "optimize"],
  },
  {
    id: "image-cropper",
    name: "Image Cropper",
    description: "Crop images to specific dimensions",
    category: "image-tools",
    icon: "crop",
    clientOnly: false,
    popular: false,
    tags: ["image", "crop", "photo"],
  },
  {
    id: "image-format-converter",
    name: "Image Format Converter",
    description: "Convert between PNG, JPG, WebP, and other formats",
    category: "image-tools",
    icon: "image",
    clientOnly: true,
    popular: true,
    tags: ["image", "format", "convert", "png", "jpg"],
  },
  {
    id: "image-to-pdf-converter",
    name: "Image to PDF Converter",
    description: "Convert multiple images to PDF document",
    category: "image-tools",
    icon: "file-image",
    clientOnly: true,
    popular: false,
    tags: ["image", "pdf", "convert", "document"],
  },
  {
    id: "background-remover",
    name: "Background Remover",
    description: "Remove image backgrounds with AI",
    category: "image-tools",
    icon: "scissors",
    clientOnly: false,
    popular: true,
    tags: ["background", "remove", "ai", "transparent"],
  },
  {
    id: "image-color-picker",
    name: "Image Color Picker",
    description: "Pick colors from uploaded images",
    category: "image-tools",
    icon: "eyedropper",
    clientOnly: true,
    popular: false,
    tags: ["color", "picker", "eyedropper", "palette"],
  },
  {
    id: "image-watermark-tool",
    name: "Image Watermark Tool",
    description: "Add text or image watermarks to photos",
    category: "image-tools",
    icon: "shield-check",
    clientOnly: true,
    popular: false,
    tags: ["watermark", "protect", "text", "logo"],
  },
  {
    id: "image-enhancer",
    name: "Image Enhancer",
    description: "Enhance images with brightness, contrast, and filters",
    category: "image-tools",
    icon: "sparkles",
    clientOnly: true,
    popular: false,
    tags: ["enhance", "filter", "brightness", "contrast"],
  },
  {
    id: "meme-generator",
    name: "Meme Generator",
    description: "Create memes with custom text on images",
    category: "image-tools",
    icon: "smile",
    clientOnly: true,
    popular: true,
    tags: ["meme", "funny", "text", "humor"],
  },
  {
    id: "image-rotator-flipper",
    name: "Image Rotator / Flipper",
    description: "Rotate and flip images in various directions",
    category: "image-tools",
    icon: "rotate-cw",
    clientOnly: true,
    popular: false,
    tags: ["rotate", "flip", "transform", "orientation"],
  },
  {
    id: "collage-maker",
    name: "Collage Maker",
    description: "Create photo collages with multiple images",
    category: "image-tools",
    icon: "grid-3x3",
    clientOnly: true,
    popular: false,
    tags: ["collage", "grid", "layout", "multiple"],
  },
  {
    id: "image-blur-pixelate",
    name: "Image Blur / Pixelate Tool",
    description: "Apply blur or pixelate effects to images",
    category: "image-tools",
    icon: "blur",
    clientOnly: true,
    popular: false,
    tags: ["blur", "pixelate", "effect", "privacy"],
  },
  {
    id: "color-picker-tool",
    name: "Color Picker Tool",
    description: "Interactive color picker with HEX and RGB values",
    category: "image-tools",
    icon: "palette",
    clientOnly: true,
    popular: false,
    tags: ["color", "hex", "rgb", "palette"],
  },

  // Document Tools
  {
    id: "pdf-merger",
    name: "PDF Merger",
    description: "Combine multiple PDFs into one",
    category: "document-tools",
    icon: "file-plus",
    clientOnly: false,
    popular: true,
    tags: ["pdf", "merge", "combine"],
  },
  {
    id: "pdf-splitter",
    name: "PDF Splitter",
    description: "Split PDF into multiple files",
    category: "document-tools",
    icon: "file-minus",
    clientOnly: false,
    popular: false,
    tags: ["pdf", "split", "separate"],
  },
  {
    id: "text-to-pdf-generator",
    name: "Text to PDF Generator",
    description: "Generate PDF documents from plain text",
    category: "document-tools",
    icon: "file-plus",
    clientOnly: true,
    popular: false,
    tags: ["text", "pdf", "generate", "document"],
  },
  {
    id: "pdf-to-word-converter",
    name: "PDF to Word Converter",
    description: "Convert PDF files to editable Word documents",
    category: "document-tools",
    icon: "file-text",
    clientOnly: false,
    popular: true,
    tags: ["pdf", "word", "convert", "doc"],
  },
  {
    id: "word-to-pdf-converter",
    name: "Word to PDF Converter",
    description: "Convert Word documents to PDF format",
    category: "document-tools",
    icon: "file-text",
    clientOnly: false,
    popular: false,
    tags: ["word", "pdf", "convert", "doc"],
  },
  {
    id: "pdf-to-excel-converter",
    name: "PDF to Excel Converter",
    description: "Extract tables from PDF to Excel spreadsheets",
    category: "document-tools",
    icon: "table",
    clientOnly: false,
    popular: false,
    tags: ["pdf", "excel", "table", "spreadsheet"],
  },
  {
    id: "excel-to-pdf-converter",
    name: "Excel to PDF Converter",
    description: "Convert Excel spreadsheets to PDF format",
    category: "document-tools",
    icon: "table",
    clientOnly: false,
    popular: false,
    tags: ["excel", "pdf", "spreadsheet", "convert"],
  },
  {
    id: "pdf-compressor",
    name: "PDF Compressor",
    description: "Reduce PDF file size while maintaining quality",
    category: "document-tools",
    icon: "minimize",
    clientOnly: false,
    popular: true,
    tags: ["pdf", "compress", "size", "optimize"],
  },
  {
    id: "ocr-tool",
    name: "OCR Tool",
    description: "Extract text from images and PDFs using OCR",
    category: "document-tools",
    icon: "scan-text",
    clientOnly: false,
    popular: true,
    tags: ["ocr", "text", "image", "scan"],
  },

  // Audio/Video Tools
  {
    id: "mp3-cutter",
    name: "MP3 Cutter",
    description: "Cut and trim audio files",
    category: "audio-video-tools",
    icon: "scissors",
    clientOnly: false,
    popular: false,
    tags: ["audio", "mp3", "cut", "trim"],
  },
  {
    id: "gif-maker",
    name: "GIF Maker",
    description: "Create animated GIFs from videos or images",
    category: "audio-video-tools",
    icon: "film",
    clientOnly: false,
    popular: true,
    tags: ["gif", "animation", "video", "images"],
  },
  {
    id: "video-downloader",
    name: "Video Downloader",
    description: "Download videos from YouTube and social media",
    category: "audio-video-tools",
    icon: "download",
    clientOnly: false,
    popular: true,
    tags: ["video", "download", "youtube", "social"],
  },
  {
    id: "video-to-mp3-converter",
    name: "Video to MP3 Converter",
    description: "Extract audio from video files as MP3",
    category: "audio-video-tools",
    icon: "music",
    clientOnly: false,
    popular: true,
    tags: ["video", "mp3", "audio", "extract"],
  },
  {
    id: "audio-converter",
    name: "Audio Converter",
    description: "Convert between various audio formats",
    category: "audio-video-tools",
    icon: "music",
    clientOnly: false,
    popular: false,
    tags: ["audio", "convert", "format", "mp3", "wav"],
  },
  {
    id: "video-compressor",
    name: "Video Compressor",
    description: "Reduce video file size while maintaining quality",
    category: "audio-video-tools",
    icon: "minimize",
    clientOnly: false,
    popular: true,
    tags: ["video", "compress", "size", "optimize"],
  },
];

export const getToolsByCategory = (category: ToolCategory): Tool[] => {
  return tools.filter(tool => tool.category === category);
};

export const getPopularTools = (): Tool[] => {
  return tools.filter(tool => tool.popular);
};

export const getToolById = (id: string): Tool | undefined => {
  return tools.find(tool => tool.id === id);
};

export const searchTools = (query: string): Tool[] => {
  const lowerQuery = query.toLowerCase();
  return tools.filter(tool => 
    tool.name.toLowerCase().includes(lowerQuery) ||
    tool.description.toLowerCase().includes(lowerQuery) ||
    tool.tags.some(tag => tag.toLowerCase().includes(lowerQuery))
  );
};

export const getCategoryColor = (category: ToolCategory): string => {
  const colorMap = {
    calculators: "calculator",
    converters: "converter",
    "image-tools": "image",
    "document-tools": "document",
    "audio-video-tools": "audio",
  };
  return colorMap[category];
};

export const getCategoryIcon = (category: ToolCategory): string => {
  const iconMap = {
    calculators: "calculator",
    converters: "repeat",
    "image-tools": "image",
    "document-tools": "file-text",
    "audio-video-tools": "play",
  };
  return iconMap[category];
};

export const toolCategories: Record<ToolCategory, { name: string; description: string; icon: string; color: string }> = {
  calculators: {
    name: "Calculators",
    description: "Mathematical and financial calculations",
    icon: "calculator",
    color: "calculator"
  },
  converters: {
    name: "Converters", 
    description: "Unit, currency, and format conversions",
    icon: "repeat",
    color: "converter"
  },
  "image-tools": {
    name: "Image Tools",
    description: "Image processing and manipulation",
    icon: "image", 
    color: "image"
  },
  "document-tools": {
    name: "Document Tools",
    description: "PDF and document utilities",
    icon: "file-text",
    color: "document"
  },
  "audio-video-tools": {
    name: "Audio/Video Tools",
    description: "Media processing and editing",
    icon: "play",
    color: "audio"
  }
};